name: conduit
description: "A minimal SSH client for Android and iOS."
publish_to: 'none'
version: 1.0.8+16

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.1"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.0
  cbor: ^6.3.7
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  dartssh2:
    git:
      url: https://github.com/gwitko/dartssh2_conduit.git
      ref: a96ee3a0d5fc55b6413ac1daf8da2a1309345a74
  conduit_vt:
    git:
      url: https://github.com/gwitko/conduit_vt.git
      ref: 294e2a3b3cb2681b7600eb143f623835370cf1c9
  dart_mosh: ^0.0.3
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.1
  uuid: ^4.5.3
  file_picker: ^11.0.2
  fido2: ^1.1.0
  flutter_nfc_kit: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: AtkynsonMonoNerdFontMono
      fonts:
        - asset: assets/fonts/AtkynsonMonoNerdFontMono-Regular.otf
